[base]
ignore = [".build", "node_modules", "private"]
rooter_patterns = ["build.sbt", ".git", "README.md"]

[default]
name = "config"
path = "$HOME/.config"

[search]
# recursively search git directories
directories = ["$HOME/Projects"]

# manual entries outside of search directories
entries = [
  "$HOME/.local/share/chezmoi",
  { path = "$HOME/Obsidian/memex", name = "interest/memex" },
  '$HOME/Library/Mobile Documents/com~apple~CloudDocs/Calibre',
]
