[base]
ignore          = [".build", "node_modules", "private"]
rooter_patterns = ["build.sbt", ".git"]

[default]
name = "home"
path = "$HOME/Downloads"

[search]
# recursively search git directories
directories = ["$HOME/Projects"]

# manual entries outside of search directories
entries = ["$HOME/.local/share/chezmoi", "$HOME/Obsidian/memex"]
