[base]
ignore          = [".build", "node_modules", "private"]
rooter_patterns = ["build.sbt", ".git", "README.md"]

[default]
name = "config"
path = "$HOME/.config"

[search]
# recursively search git directories
directories = ["$HOME/Projects"]

# manual entries outside of search directories
entries = [
  { name = "config/chezmoi", path = "$HOME/.local/share/chezmoi" },
  { name = "interests/books", path = "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Calibre" },
  { name = "interests/memex", path = "$HOME/Obsidian/memex" },
  { name = "interests/spanish", path = "$HOME/Obsidian/memex/20 Areas/Interests/Spanish" },
]
